language: node_js
sudo: required

services:
  - docker

node_js:
  - 10
addons:
  apt:
    packages:
    - sshpass


env:
  - IMAGE_NAME=sosconf/frontend:2019

script:
  - docker pull "$IMAGE_NAME" || true
  - docker build --cache-from "$IMAGE_NAME"
      --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      --build-arg VCS_REF="$TRAVIS_COMMIT"
      -t "build/$IMAGE_NAME" -f ./Dockerfile .
  - docker run -d -P --name temp "build/$IMAGE_NAME"
  - docker rm -f temp || true

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD_SECURE";
      docker tag "build/$IMAGE_NAME" "$IMAGE_NAME";
      docker push "$IMAGE_NAME";
      #sshpass -p ${DEPLOY_PASSWD} ssh -o "StrictHostKeyChecking no" root@${DEPLOY_IP} "cd sosconf-2019/ && ./deploy.sh";
    fi


  - if [[ "$TRAVIS_BRANCH" == "dev" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD_SECURE";
      docker tag "build/$IMAGENAME" "$IMAGE_NAME:dev";
      docker push "$IMAGE_NAME:dev";
    fi
